### ISSUE TITLE
read_abs(cat_no="8501.0", tables=c(23))

### ISSUE THREAD

**Issue by ekurniawan-ispt** [MattCowgill/readabs#96]
Running ```read_abs(cat_no="8501.0", tables=c(23))``` should work but it has resulted the following error:
```
Finding filenames for tables corresponding to ABS catalogue 8501.0 Error in utils::download.file(url = url, mode = "wb", quiet = !show_progress_bars,  : 
  cannot open URL 'https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retail turnover.xls'
Finding filenames for tables corresponding to ABS catalogue 8501.0
Attempting to download files from catalogue 8501.0, Retail Trade, Australia
trying URL 'https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retail turnover.xls'
Error in utils::download.file(url = url, mode = "wb", quiet = !show_progress_bars,  : 
  cannot open URL 'https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retail turnover.xls'
In addition: Warning message:
In utils::download.file(url = url, mode = "wb", quiet = !show_progress_bars,  :
  cannot open URL 'https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/sep-2020/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retailturnover.xls': HTTP status was '404 Not Found'
```

It works when taking the URL ```https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retail turnover.xls``` to a browser.

Furthermore, ```read_abs(cat_no="8501.0", tables=c(22))```  runs without problem.
The [ABS Catalog 8501.0](https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release#data-download) says table no goes up to table 23.

**Comment by MattCowgill** [comment]
Thanks @ekurniawan-ispt I'll look into it

**Comment by MattCowgill** [comment]
Hi @ekurniawan-ispt it looks to me like the problem is that there's a space in the URL between `retail` and `turnover`. I'll see if I can fix this; if not I will ask the ABS to fix it. Thanks

**Comment by MattCowgill** [comment]
Hi @ekurniawan-ispt, this issue is now fixed in the Github version of the package. Upgrade using:
`devtools::install_github("mattcowgill/readabs")`

I will submit an update to CRAN in the coming days.


``` r
readabs::read_abs(cat_no="8501.0", tables=23)
#> Finding filenames for tables corresponding to ABS catalogue 8501.0
#> Attempting to download files from catalogue 8501.0, Retail Trade, Australia
#> Extracting data from downloaded spreadsheets
#> Tidying data from imported ABS spreadsheets
#> # A tibble: 261 x 12
#>    table_no sheet_no table_title date       series value series_type data_type
#>    <chr>    <chr>    <chr>       <date>     <chr>  <dbl> <chr>       <chr>    
#>  1 table_2… Data1    TABLE 23 O… 2013-07-01 % of …   1.2 Original    PERCENT  
#>  2 table_2… Data1    TABLE 23 O… 2013-07-01 % of …   3.2 Original    PERCENT  
#>  3 table_2… Data1    TABLE 23 O… 2013-07-01 % of …   2.1 Original    PERCENT  
#>  4 table_2… Data1    TABLE 23 O… 2013-08-01 % of …   1.2 Original    PERCENT  
#>  5 table_2… Data1    TABLE 23 O… 2013-08-01 % of …   3.2 Original    PERCENT  
#>  6 table_2… Data1    TABLE 23 O… 2013-08-01 % of …   2.1 Original    PERCENT  
#>  7 table_2… Data1    TABLE 23 O… 2013-09-01 % of …   1.2 Original    PERCENT  
#>  8 table_2… Data1    TABLE 23 O… 2013-09-01 % of …   3.3 Original    PERCENT  
#>  9 table_2… Data1    TABLE 23 O… 2013-09-01 % of …   2.2 Original    PERCENT  
#> 10 table_2… Data1    TABLE 23 O… 2013-10-01 % of …   1.1 Original    PERCENT  
#> # … with 251 more rows, and 4 more variables: collection_month <chr>,
#> #   frequency <chr>, series_id <chr>, unit <chr>
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MattCowgill** [comment]
Please let me know if that works for you @ekurniawan-ispt.

**Comment by ekurniawan-ispt** [comment]
Thanks for the prompt response! 
However, I'm still getting the error in my environment after reinstalling from the latest release:
![image](https://user-images.githubusercontent.com/56810684/98329700-efefb700-204c-11eb-816a-7a78ec3c4700.png)

**Comment by ekurniawan-ispt** [comment]
I might restart my whole system. And test again.

**Comment by ekurniawan-ispt** [comment]
It works fine with ```readabs::read_abs(cat_no="8501.0", tables=22)``` though.
![image](https://user-images.githubusercontent.com/56810684/98329888-58d72f00-204d-11eb-9164-8c8d096dfc4d.png)

**Comment by MattCowgill** [comment]
Hi @ekurniawan-ispt, did you restart your R session after installing the new version of `readabs`?

**Comment by ekurniawan-ispt** [comment]
No, that's what I'm going to do which is Restart.

**Comment by MattCowgill** [comment]
OK, thanks. You shouldn't need to restart your whole system, just your R session. If you're using RStudio, click the `Session` menu, then `Restart R`.

**Comment by ekurniawan-ispt** [comment]
It works now!! Thanks heaps!!

**Comment by MattCowgill** [comment]
Great, glad to hear it. Please let me know if you encounter any other issues.

**Comment by ekurniawan-ispt** [comment]
Hi @MattCowgill , I'm sorry, but this ```readabs::read_abs(cat_no="8501.0", tables=23)``` is erroring again unfortunately.
```
Finding filenames for tables corresponding to ABS catalogue 8501.0 Error in utils::download.file(url = urls, mode = "wb", quiet = !show_progress_bars,  : 
  cannot open URL 'https://www.abs.gov.au/statistics/industry/retail-and-wholesale-trade/retail-trade-australia/latest-release/table_23_online_retail_turnover_australia_by_type_of_activity_percentage_of_total_australian_retail turnover.xls'
```
This would have to wait till Monday next week for ABS?

**Comment by ekurniawan-ispt** [comment]
Now it works....hmmm...

**Comment by MattCowgill** [comment]
Have you had any further problems with this?

**Comment by ekurniawan-ispt** [comment]
Yes, our ABS data pipeline (powered by readabs and Databricks) finally finished successfully in prod env when I re-ran it on Saturday morning.
It failed on Friday evening which made me nervous. 
Anyway thanks for readabs R package you have developed!

**Comment by MattCowgill** [comment]
Great, glad to hear it @ekurniawan-ispt. Thank you, glad you have found use for the package.
